openapi: 3.0.1
x-nhs-api-spec-guid: fac3b3c9-638c-4a00-aa4b-3c7172abe80b
info:
  title: Electronic Transmission of Prescriptions (ETP) data service
  description: |-
    ## Overview
    Use this API to search for dispensers that use the Electronic Prescription Service (EPS).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis).

    ## Network access
    This API is available on the internet. An API key is required to access this API. Information on how to obtain an API key can be found on the [NHS website developer portal](https://developer.api.nhs.uk/).
  contact:
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  license:
    name: MIT
  version: 1.0.0
x-spec-publication:
  try-this-api:
    disabled: true
servers:
  - url: 'https://api.nhs.uk/etp'
paths:
  /SearchByName:
    get:
      summary: Search dispensers by name
      description: |-
        Get the first 25 dispensers matching the given name.

        The name will be a match if the dispenser name **starts with** the given `organisationName` value. For example, a search on 'Coens' could return a dispenser with the name of 'Coens Plc' but not with the name of 'The Coens Chemist'.

        The returned list is filtered by the specified service type and whether the dispenser uses EPS. The list is ordered alphabetically by the dispenser name.

        This is not a geographical search and will return any dispensaries within England that meet the search criteria.
      operationId: SearchByName
      parameters:
        - name: organisationName
          in: query
          description: The name of the dispenser to search on (e.g. 'Boots')
          required: true
          schema:
            type: string
        - name: serviceType
          in: query
          description: |-
            The service type to search for. Value is either:
             * '1' for Community Pharmacy (including Internet Pharmacy), or
             * '2' for Dispensing Appliance Contractor.
          required: true
          schema:
            type: string
        - name: eps
          in: query
          description: |-
            Value indicating whether to include dispensers using EPS. Value is either:
             * 'YES' to include only dispensers using EPS (default), or
             * 'NO' to include only dispensers not using EPS.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pharmacyModel'
        '400':
          description: One or more of the required parameters were not provided
  /SearchByNameAndLocation:
    get:
      summary: Search dispensers by name and location
      description: |-
        Get the first 25 dispensers matching the given `organisationName` and either the given `partPostcode` or `location`.

        The name will be a match if the dispenser name **starts with** the given `organisationName` value. For example, a search on 'Coens' could return a dispenser with the name of 'Coens Plc' but not with the name of 'The Coens Chemist'.

        The part postcode will be a match if the dispenser postcode **starts with** the given `partPostcode` value. For example, a search on 'LS1' could return a dispenser with postcode 'LS1 4DT' or with postcode 'LS11 8BB'. No dispensaries in surrounding postcodes will be returned even if there are less than 25 in the supplied part postcode results.

        The location will be a match if any of the four lines of the dispenser's address **contain** the given `location` value. For example, a search on 'Derby' could return a dispenser with an address line of 'Derby', or 'Derbyshire', or '13 Derby Street'.

        The returned list is filtered by the specified service type and whether the dispenser uses EPS. The list is ordered alphabetically by the dispenser name.

        This is not a geographical search and will return any dispensaries within England that meet the search criteria.
      operationId: SearchByNameAndLocation
      parameters:
        - name: organisationName
          in: query
          description: The name of the pharmacy to search on (e.g. Boots)
          required: true
          schema:
            type: string
        - name: partPostcode
          in: query
          description: First Part of a valid postcode to search on
          schema:
            type: string
        - name: location
          in: query
          description: Street name or town name to search
          schema:
            type: string
        - name: serviceType
          in: query
          description: |-
            The service type to search for. Value is either:
             * '1' for Community Pharmacy (including Internet Pharmacy), or
             * '2' for Dispensing Appliance Contractor.
          required: true
          schema:
            type: string
        - name: eps
          in: query
          description: |-
            Value indicating whether to include dispensers using EPS. Value is either:
             * 'YES' to include only dispensers using EPS (default), or
             * 'NO' to include only dispensers not using EPS.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pharmacyModel'
        '400':
          description: One or more of the required parameters were not provided
  /SearchByOdsCode:
    get:
      summary: Get dispenser by ODS code
      description: |-
        Get the single dispenser with the requested ODS code.

        If the ODS code of a dispenser is already known, this endpoint can be used to:
         * Verify that the ODS code is for a valid dispenser. Only    organisations registered as a dispenser will be returned    (i.e. if a valid ODS code is supplied but it is not    registered as a dispenser, then no data will be    returned).
         * Check that the ODS code is for the intended dispenser,    e.g. the returned organisation has the expected name and    address.
         * Confirm that the dispenser uses EPS
      operationId: SearchByOdsCode
      parameters:
        - name: odsCode
          in: query
          description: 'Valid ODS Code (e.g. FLH84, FHH81, FW866)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pharmacyModel'
        '204':
          description: The ODS code was not found or is not for a dispenser
        '400':
          description: The ODS code is null or empty
  /SearchByPostcode:
    get:
      summary: Search dispensers by postcode
      description: |-
        Get the first 25 nearest dispensers to the given postcode.

        The returned list is filtered by the specified service type and whether the dispenser uses EPS. The list is ordered by distance from the given postcode.
      operationId: SearchByPostcode
      parameters:
        - name: fullPostcode
          in: query
          description: Full postcode to search on
          required: true
          schema:
            type: string
        - name: serviceType
          in: query
          description: |-
            The service type to search for. Value is either:
             * '1' for Community Pharmacy (including Internet Pharmacy), or
             * '2' for Dispensing Appliance Contractor.
          required: true
          schema:
            type: string
        - name: eps
          in: query
          description: |-
            Value indicating whether to include dispensers using EPS. Value is either:
             * 'YES' to include only dispensers using EPS (default), or
             * 'NO' to include only dispensers not using EPS.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pharmacyModel'
        '400':
          description: One or more of the required parameters were not provided
  /SearchInternetPharmacy:
    get:
      summary: Get all internet pharmacies
      description: |-
        Get all internet pharmacies providing services in England.

        The returned list is ordered alphabetically by the dispenser name
      operationId: SearchInternetPharmacy
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/internetPharmacyModel'
components:
  schemas:
    internetPharmacyModel:
      type: object
      properties:
        organisationCode:
          type: string
          description: ODS code for the dispensing site.
        name:
          type: string
          description: Name of the dispensing site.
        phone:
          type: string
          description: 'Telephone number of the dispensing site, if available.'
          nullable: true
        fax:
          type: string
          description: 'Fax number of the dispensing site, if available.'
          nullable: true
        street:
          type: string
          description: 'First address line of the dispensing site, if available.'
          nullable: true
        locality:
          type: string
          description: 'Second address line of the dispensing site, if available.'
          nullable: true
        town:
          type: string
          description: 'Third address line of the dispensing site, if available.'
          nullable: true
        administrative:
          type: string
          description: 'Fourth address line of the dispensing site, if available.'
          nullable: true
        postcode:
          type: string
          description: 'Postcode of the dispensing site, if available.'
          nullable: true
        url:
          type: string
          description: 'URL for the website of the dispenser, if available.'
          nullable: true
        eps:
          type: boolean
          description: |-
            Value indicating if the dispensing site uses EPS.  
            Value is true if uses EPS, otherwise false.
        serviceType:
          type: string
          description: |-
            Type of service provided by the dispensing site. Value is either:
             * '1' for Community Pharmacy (including Internet Pharmacy), or
             * '2' for Dispensing Appliance Contractor.
        services:
          type: array
          items:
            $ref: '#/components/schemas/serviceModel'
          description: List of services provided by the dispensing site.
      example:
        organisationCode: FM813
        name: Online Pharmacy
        phone: 01234 567890
        fax: null
        street: 123 West Drive
        locality: Beeston
        town: Broxtowe
        administrative: Nottinghamshire
        postcode: NG7 2QW
        url: 'https://example.com'
        eps: true
        serviceType: '1'
        services:
          - serviceName: 'Pharmacy Service: Multi-lingual staff'
            serviceCode: SRV0524
            serviceProvider: '{}'
          - serviceName: 'Pharmacy Service: Prescription delivery service'
            serviceCode: SRV0522
            serviceProvider: '{}'
    openingTimesModel:
      type: object
      properties:
        weekDay:
          type: string
          description: |-
            Day of the week, e.g. 'Monday'.  
            Value is undefined if `openingTimeType` is 'Additional'.
          nullable: true
        times:
          type: string
          description: |-
            Opening times range in format 'hh:mm-hh:mm', e.g. '09:00-12:00'.  
            Value is undefined if `isOpen` is false.
          nullable: true
        offsetOpeningTime:
          type: string
          description: |-
            Opening time as number of minutes since midnight.  
            Value is undefined if `isOpen` is false.
          nullable: true
        offsetClosingTime:
          type: string
          description: |-
            Closing time as number of minutes since midnight.  
            Value is undefined if `isOpen` is false.
          nullable: true
        openingTimeType:
          type: string
          description: |-
            Type of opening time session. Value is either:
             * 'General' for normal opening times by day of week, or
             * 'Additional' for opening times for the specific date in `additionalOpeningDate`.
        additionalOpeningDate:
          type: string
          description: |-
            Date for additional opening times, such as bank holiday opening times, which replace the normal opening times on this date.  
            Date is in format 'MMM  d YYYY', e.g. 'Apr 15 2022', 'Jun  2 2022'. Note that there may be an extra space between the month name and the day of the month if the day of the month is a single digit.  
            Value is undefined if `openingTimeType` is 'General'.
          nullable: true
        isOpen:
          type: boolean
          description: |-
            Value indicating if the service is open or closed on either the day of the week specified in `weekDay` or the date specified in `additionalOpeningDate`.  
            Value is true if open, otherwise false.
      example:
        weekDay: Monday
        times: '09:00-17:00'
        offsetOpeningTime: '540'
        offsetClosingTime: '1020'
        openingTimeType: General
        additionalOpeningDate: ''
        isOpen: true
    pharmacyModel:
      type: object
      properties:
        organisationCode:
          type: string
          description: ODS code for the dispensing site.
        name:
          type: string
          description: Name of the dispensing site.
        phone:
          type: string
          description: 'Telephone number of the dispensing site, if available.'
          nullable: true
        fax:
          type: string
          description: 'Fax number of the dispensing site, if available.'
          nullable: true
        street:
          type: string
          description: 'First address line of the dispensing site, if available.'
          nullable: true
        locality:
          type: string
          description: 'Second address line of the dispensing site, if available.'
          nullable: true
        town:
          type: string
          description: 'Third address line of the dispensing site, if available.'
          nullable: true
        administrative:
          type: string
          description: 'Fourth address line of the dispensing site, if available.'
          nullable: true
        postcode:
          type: string
          description: 'Postcode of the dispensing site, if available.'
          nullable: true
        url:
          type: string
          description: 'URL for the website of the dispenser, if available.'
          nullable: true
        eps:
          type: boolean
          description: |-
            Value indicating if the dispensing site uses EPS.  
            Value is true if uses EPS, otherwise false.
        serviceType:
          type: string
          description: |-
            Type of service provided by the dispensing site. Value is either:
             * '1' for Community Pharmacy (including Internet Pharmacy), or
             * '2' for Dispensing Appliance Contractor.
        distance:
          type: number
          description: Approximate straight line distance in miles from the search location to the dispensing site. Only applicable for a geographical search.
          format: double
        services:
          type: array
          items:
            $ref: '#/components/schemas/serviceModel'
          description: List of services provided by the dispensing site.
        openingTimes:
          type: array
          items:
            $ref: '#/components/schemas/openingTimesModel'
          description: List of opening times of the dispensing site.
      example:
        organisationCode: FX987
        name: ABC Pharmacy
        phone: 01234 567890
        fax: null
        street: 123 West Drive
        locality: Beeston
        town: Broxtowe
        administrative: Nottinghamshire
        postcode: NG7 2QW
        url: 'https://example.com'
        eps: true
        serviceType: '1'
        distance: 0.123456789
        services:
          - serviceName: 'Pharmacy Service (NHS): Minor ailment service'
            serviceCode: SRV0198
            serviceProvider: '{}'
          - serviceName: 'Pharmacy Service (NHS): Medication review service'
            serviceCode: SRV0261
            serviceProvider: '{}'
          - serviceName: 'Pharmacy Service (NHS): Stop smoking service'
            serviceCode: SRV0273
            serviceProvider: '{}'
        openingTimes:
          - weekDay: Monday
            times: '09:00-17:00'
            offsetOpeningTime: '540'
            offsetClosingTime: '1020'
            openingTimeType: General
            additionalOpeningDate: ''
            isOpen: true
          - weekDay: ''
            times: '12:00-18:00'
            offsetOpeningTime: '12:00'
            offsetClosingTime: '18:00'
            openingTimeType: Additional
            additionalOpeningDate: Apr  1 2022
            isOpen: true
          - weekDay: ''
            times: ''
            offsetOpeningTime: ''
            offsetClosingTime: ''
            openingTimeType: Additional
            additionalOpeningDate: Apr 15 2022
            isOpen: false
    serviceModel:
      type: object
      properties:
        serviceName:
          type: string
          description: Name of the service.
        serviceCode:
          type: string
          description: NHS Website service reference code. Can be used with some NHS Website APIs.
        serviceProvider:
          type: string
          description: |-
            String representation of a JSON object containing details of the service provider, if the service is not directly provided by the dispenser.  
            In almost all cases no additional service provider details are available, and the value will contain the string representation of an empty object, i.e. '{}'.
      example:
        serviceName: 'Pharmacy Service (NHS): Minor ailment service'
        serviceCode: SRV0198
        serviceProvider: '{}'
